import { describe, expect, it } from 'bun:test';
import { createCipheriv } from 'node:crypto';
import { decryptInfo, generateSignature } from '../src/credentials';
import { extractFilamentInfo, extractThumbnail, parseEstimatedTime, parseLayerHeights } from '../src/gcode';

const sample = Buffer.from(
    [
        '; generated by OrcaSlicer',
        '; thumbnail begin 16x16 40',
        '; aGVsbG8=',
        '; d29ybGQ=',
        '; thumbnail end',
        'T1',
        'G1 X10',
        '; filament_colour = #FF0000;#00FF00;#0000FF',
        '; filament_type = PLA;PETG;TPU',
        '; layer_height = 0.2',
        '; initial_layer_print_height = 0.25',
        '; total estimated time: 1h 9m 20s',
    ].join('\n'),
);

describe('gcode parsing', () => {
    it('estimated time', () => {
        expect(parseEstimatedTime(sample)).toBe(3600 + 9 * 60 + 20);
    });
    it('layer heights', () => {
        expect(parseLayerHeights(sample)).toEqual({ layerHeight: 0.2, firstLayerHeight: 0.25 });
    });
    it('thumbnail', () => {
        expect(extractThumbnail(sample)).toBe('aGVsbG8=d29ybGQ=');
    });
    it('filaments with tool usage', () => {
        const f = extractFilamentInfo(sample);
        expect(f).toHaveLength(3);
        expect(f[1]).toMatchObject({ colorHex: '#00FF00', material: 'PETG', isUsed: true });
        expect(f[0].isUsed).toBe(false);
    });
});

describe('credentials', () => {
    it('signature is deterministic', () => {
        expect(generateSignature('0123456789abcdef0123456789abcdef', 1700000000000, 'abc123')).toMatch(
            /^[0-9a-f]{32}$/,
        );
    });
    it('round-trips AES-128-CBC', () => {
        const key = 'sixteen byte key';
        const iv = 'sixteen byte iv!';
        const c = createCipheriv('aes-128-cbc', key, iv);
        const enc = Buffer.concat([c.update(JSON.stringify({ username: 'user1' })), c.final()]).toString('base64');
        expect(decryptInfo(enc, key, iv)).toEqual({ username: 'user1' });
    });
});
